apiVersion: v1
kind: Service
metadata:
  name: mokolee-web-service
  labels:
    app: mokolee-web
spec:
  type: LoadBalancer
  selector:
    app: mokolee-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
