apiVersion: apps/v1
kind: Deployment
metadata:
  name: mokolee-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mokolee-web
  template:
    metadata:
      labels:
        app: mokolee-web
    spec:
      containers:
      - name: web-container
        image: beendoo/want-piece:latest
        ports:
        - containerPort: 80
