apiVersion: apps/v1
kind: Deployment
metadata:
  name: mokolee-was-deployment
  labels:
    app: mokolee-was
spec:
  replicas: 2  # 원하는 복제본 수
  selector:
    matchLabels:
      app: mokolee-was
  template:
    metadata:
      labels:
        app: mokolee-was
    spec:
      containers:
      - name: was-container
        image: beendoo/want-piece-was:latest  # 빌드된 Docker 이미지
        ports:
        - containerPort: 8080  # WAS가 사용하는 포트
        env:
        - name: DB_HOST
          value: "<DB 주소>"  # WAS에서 사용할 DB 주소 설정
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username  # 시크릿에서 DB 사용자명 가져오기
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password  # 시크릿에서 DB 비밀번호 가져오기
